### ISSUE TITLE
docs.rs documentation link to 

### ISSUE THREAD

**Issue by tim-seoss** [probe-rs/cargo-embed#164]
In this page: https://docs.rs/crate/cargo-embed/0.10.1 there is a link to `default.toml` - which points at https://docs.rs/crate/cargo-embed/src/config/default.toml 

... but this is a broken link.

The surrounding text is:

`You can find all available options in the default.toml. Commented out options are the ones that are None by default.`

**Comment by Yatekii** [comment]
Oh, yeah, it should be https://github.com/probe-rs/cargo-embed/blob/master/src/config/default.toml actually :/
