### ISSUE TITLE
Build fails due to probe-rs renames

### ISSUE THREAD

**Issue by dbrgn** [probe-rs/cargo-embed#168]
See https://github.com/probe-rs/probe-rs/pull/482.

**Comment by Yatekii** [comment]
This is fixed already and is not cargo-embed related but probe-rs-rtt :)

**Comment by noppej** [comment]
@Yatekii Thank you for fixing this. I have a 'newbie' question ... can you please give me some pointers on how I can install cargo-embed with this new version of probe-rs-rtt?

**Comment by Yatekii** [comment]
@noppej you should be able to install with `cargo install --git https://github.com/probe-rs/cargo-embed`. Let me know if this works :)

**Comment by noppej** [comment]
Thanks, but it fails with the same error ... I don't know how to make it pick up the right version of probe-rs-rtt.

```
   Compiling probe-rs-rtt v0.10.1 (https://github.com/probe-rs/probe-rs-rtt#b06d69d7)
error[E0599]: no variant or associated item named `Nvm` found for enum `probe_rs::config::MemoryRegion` in the current scope
   --> /Users/Jack/.cargo/git/checkouts/probe-rs-rtt-7666cc4c60dc073f/b06d69d/probe-rs-rtt/src/channel.rs:383:27
    |
383 |             MemoryRegion::Nvm(r) => Some(&r.range),
    |                           ^^^ variant or associated item not found in `probe_rs::config::MemoryRegion`

```

**Comment by Yatekii** [comment]
So this failed because patch versions are ignored when you install with --git apparently. if you try again, this should hopefully work :)

**Comment by dbrgn** [comment]
> This is fixed already and is not cargo-embed related but probe-rs-rtt :)

Whoops, sorry! :slightly_smiling_face:

**Comment by dbrgn** [comment]
@noppej maybe you also need a `cargo update`.

**Comment by noppej** [comment]
Thank you @Yatekii ... the patch thing fixed. Much appreciated!
