### ISSUE TITLE
When RTT is cut, cargo-embed cannot be stopped with CTRL+C

### ISSUE THREAD

**Issue by kuon** [probe-rs/cargo-embed#207]
I have a firmware that I go into STOP mode under some conditions. I am testing those and sending it into STOP mode when connected to the debugger.

When this happen while `cargo-embed` is connected via RTT, the terminal is flooded (look at attached image). And except killing cargo from another terminal, there is no way to stop it.

It would be helpful if I could just CTRL+C to stop it when it's flooding. And it would even be better to stop the flood altogether, and just have a single log line that the connection was interrupted.

![image](https://user-images.githubusercontent.com/160200/113016554-e3e0cf00-917e-11eb-9514-baeac8f2b808.png)

**Comment by Yatekii** [comment]
Please provide more info about your enviroment. Ctrl+C works fine for me.

**Comment by Yatekii** [comment]
Very odd.
Maybe my memory is bad then :/

**Comment by willemml** [comment]
I am having the same issue on 0.10.1.
I am using macOS 11.2 and an STLink V3SET with an STM32F730V8T6.

**Comment by Tiwalun** [comment]
I was able to reproduce this, on Ubuntu 21.04.

Probe: ST-Link v2
Terminals: gnome-terminal, alacritty
Chip: stm32f412zg

The problem seems to occur when the WFI instruction is used. See also probe-rs/probe-rs#350. Just unplugging the probe does not seem to cause this, in that case CTRL-C works.
