### ISSUE TITLE
Missing 0.10.0 and 0.10.1 git tags

### ISSUE THREAD

**Issue by roblabla** [probe-rs/cargo-embed#219]
Heyo,

The git tags for 0.10.0 and 0.10.1 hasn't been pushed (the last tag in the repo is v0.9.1). This is making packaging the update in NixOS difficult (see https://github.com/NixOS/nixpkgs/pull/122513).

AFAIK, 0.10.1 is 56091e84f70ab2263f890628f76d8f73113a6343, while 0.10.0 is 8a4c101d22b0e2e83e85c2af8689f837e7324f5a. Could they be tagged?

Thanks!

**Comment by Yatekii** [comment]
Thanks for reporting this and sorry for the missing tags/releases. I fixed this.
