### ISSUE TITLE
Version release disparity from `crates.io`

### ISSUE THREAD

**Issue by jonnyando** [probe-rs/cargo-embed#223]
I noticed on `crates.io` that version `0.10.1` was released on the 23rd of November 2020, and yet this repo shows the git tag release of `0.10.1` for just last week. It looks like the git and crates.io release versions have been out of sync (for their release date) for a few versions now.

What's up with that?

**Comment by Yatekii** [comment]
I just forgot to tag the release back in November because normally I and most other people install through crates.io anyways. both 0.10.1 point to the exact same commit :)
