### ISSUE TITLE
compile error of a simple project when using cargo-embed 

### ISSUE THREAD

**Issue by Orca-bit** [probe-rs/cargo-embed#224]
Hi, I‘m a very beginner, I try to compile a project from the [Discovery book chap.5](https://docs.rust-embedded.org/discovery/05-led-roulette/index.html) using cargo-embed. I put the [auxiliary](https://github.com/rust-embedded/discovery/tree/master/src/05-led-roulette/auxiliary) folder under my own project path, and in my `Cargo.toml`, 
```
[dependencies]
aux5 = { path = "auxiliary" }
```
in my `src/main.rs`:
```rust
#![deny(unsafe_code)]
#![no_main]
#![no_std]

use aux5::{entry, Delay, DelayMs, LedArray, OutputSwitch};

#[entry]
fn main() -> ! {
    let (mut delay, mut leds): (Delay, LedArray) = aux5::init();

    let ms = 50_u16;

    leds[0].on().ok();
    loop {
        for curr in 0..8 {
            let next = (curr + 1) % 8;

            leds[next].on().ok();
            delay.delay_ms(ms);
            leds[curr].off().ok();
            delay.delay_ms(ms);
        }
    }
}
```
Everything goes very well using cargo-embed to build until compilng the src/main.rs, the Cargo emphsis an error: 
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" ... ...
```
I really need some help. Is there any thing I have missed?

**Comment by Yatekii** [comment]
Hey!

The issue you are hitting is a general one with `cargo build`. `cargo embed` litterally calls `cargo build` which the fails at the linking step.

You are showing very little of the rest of the error output and your project setup, so it's hard for me to tell what the exact issue is. A good asking place would be `matrix.org#rust-embedded` :)
