### ISSUE TITLE
Unhandled panic when exiting on Windows

### ISSUE THREAD

**Issue by jonnyando** [probe-rs/cargo-embed#241]
**Describe the bug**
After running successfully and hitting ctrl+c, the RTT terminal closes and the following lines are printed:
``` 
thread panicked while processing panic. aborting.
The terminal process "C:\Users\Jon\.cargo\bin\cargo.exe 'embed', '--chip', 'STM32F446RETx'" terminated with exit code: 3221225501.
```
No logging info is saved to the directory specified in `Embed.toml` either.

**To Reproduce**
1. I run `cargo embed --chip STM32F446RETx`
2. After the RTT terminal has run and my program prints some logs, I hit `ctrl+c`

**Expected behavior**
I expect `cargo-embed` to exit successfully and the logs saved to the target directory.

**Stacktrace**
See above for console output.

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
This is with release `0.11.0` installed from crates-io, and when built locally.
I also tried compiling with `--features sentry` and `--no-default-features`, both having the same outcome.

**Comment by Tiwalun** [comment]
Thanks for reporting this!

Could you try the fix in #242? With that, the panic should not happen.
