### ISSUE TITLE
Allow more precise options for selecting the probe

### ISSUE THREAD

**Issue by mvirkkunen** [probe-rs/cargo-embed#3]
`probe-index` is probably not stable and depends on the order in which things are enumerated. It would be nice to have options like USB VID/PID and serial number to identify which probe to use.

**Comment by Yatekii** [comment]
We have discussed this before and this would be great to have :) Thanks for opening an issue!

**Comment by Yatekii** [comment]
Fixed in #4.

**Comment by mvirkkunen** [comment]
Very nice :D
