### ISSUE TITLE
.embed.local.* not loaded

### ISSUE THREAD

**Issue by mattiasgronlund** [probe-rs/cargo-embed#30]
It is stated in , that .embed.local.* should be merged to the configuration when cargo embed ... is used, but these files will never be loaded as of https://github.com/mehcode/config-rs/issues/101.

**To Reproduce**
1. Create a new file .embed.local.toml, with an updated log_level
2. run cargo embed

**Expected behavior**
Log level should be changed

**Stacktrace**
N/A

**Desktop (please complete the following information):**
 - macOS Mojave

**Additional context**
I have created a patch for the config crate, but when I use that one a non related "bug" manifest itself as part of upgrading config crate version, with the updated config crate, the values for std::log::Level is required to be in upper case instead of Pascal case.

But there exists a workaround, where one extra try is done with a _dummy_ extension is added, so that the config-trait has one to remove...

**Comment by Yatekii** [comment]
Fixed in #31 :)
