### ISSUE TITLE
 `cargo embed -V` does not provide version number

### ISSUE THREAD

**Issue by sid2934** [probe-rs/cargo-embed#389]
**Describe the bug**
The  `cargo embed -V` command simply prints "cargo-embed" to the console with no indication of the version number running.
This is happening in Windows Terminal on Windows 11 Pro Build Version	10.0.22000 Build 22000
 

**To Reproduce**
1. Execute `cargo install cargo-embed` (Executed on October 14, 2022 likely installed version 0.13.0)
2. Run `cargo embed -V` or `cargo embed --version`

**Expected behavior**
Expected result should have the version number included in the output

**Desktop**
Windows 11 Pro Build Version	10.0.22000 Build 22000

**Comment by dbrgn** [comment]
Hehe, just ran across this issue as well, you were 1h faster in reporting 🙂

**Comment by dbrgn** [comment]
The reason is that clap takes over handling of the version argument. I'll send a fix.

**Comment by sid2934** [comment]
That was the fastest turn around for an issue I have ever filed. Thanks for the fix!
