### ISSUE TITLE
Does not compile on Windows due to the `termion` dependency

### ISSUE THREAD

**Issue by timokroeger** [probe-rs/cargo-embed#6]
Blocked by: https://gitlab.redox-os.org/redox-os/termion/-/merge_requests/151
It says "Edit: It's all done and ready now" but it’s been open for more than 1.5 years already.

I would totally use the `cargo-embed` on windows even with plain non-colored output and missing progress bars.

**Comment by Tiwalun** [comment]
An other option would be to use [crossterm](https://crates.io/crates/crossterm) instead of `termion`, which should work on Windows.

**Comment by Yatekii** [comment]
Fixed in #11.
