### ISSUE TITLE
Error installing cargo-embed and cargo-flash

### ISSUE THREAD

**Issue by fnafnio** [probe-rs/cargo-embed#63]
When installing cargo-flash or cargo-embed I get 

error: linking with `link.exe` failed: exit code: 1181
and
`note: LINK : fatal error LNK1181: cannot open input file 'ftdi1.lib'`

I am on
 - Windows 10 Build 18363
 - rustc 1.46.0 (stable)

With 0.8.0 there is no issue installing.
I'd be glad to provide more information if needed

**Comment by Tiwalun** [comment]
Version 0.9.0 adds support for FTDI based probes, and requires libftdi as a new dependency. See https://github.com/probe-rs/probe-rs#building for setup instructions.

This is still missing from the cargo-embed and cargo-flash readme files.
